#!/usr/bin/env python3
"""
HBase Ingestion Script
Populates the HBase 'customer_rfm_features' table with feature vectors 
from customers.csv and computed RFM features.
Generates an HBase batch script (load_hbase.hb) containing 'put' statements.
"""
import csv
from datetime import datetime

REFERENCE_DATE = datetime(2026, 8, 1)

def load_data():
    # 1. Read Customers metadata
    cust_meta = {}
    with open('../data/customers.csv', 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            cust_meta[row['customer_id']] = row

    # 2. Read Purchases and compute RFM per customer
    cust_rfm = {}
    with open('../data/purchases.csv', 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            cid = row['customer_id']
            odate = datetime.strptime(row['order_date'], '%Y-%m-%d')
            amt = float(row['amount'])
            
            if cid not in cust_rfm:
                cust_rfm[cid] = {'latest_date': odate, 'freq': 1, 'monetary': amt}
            else:
                cust_rfm[cid]['freq'] += 1
                cust_rfm[cid]['monetary'] += amt
                if odate > cust_rfm[cid]['latest_date']:
                    cust_rfm[cid]['latest_date'] = odate

    # 3. Generate HBase put commands
    hbase_cmds = ["# Batch Load generated by 04_hbase_load.py"]
    
    for cid, meta in cust_meta.items():
        if cid in cust_rfm:
            rfm = cust_rfm[cid]
            recency = (REFERENCE_DATE - rfm['latest_date']).days
            freq = rfm['freq']
            monetary = round(rfm['monetary'], 2)
            
            # Simple segmentation logic for HBase seed
            if recency <= 30 and freq >= 5:
                segment = "Champions"
            elif recency <= 60 and freq >= 3:
                segment = "Loyal Customers"
            elif recency > 90:
                segment = "Lost / Churned"
            else:
                segment = "Potential Loyalists"
                
            is_churned = "1" if recency > 90 else "0"
            
            # Demographics
            hbase_cmds.append(f"put 'customer_rfm_features', '{cid}', 'cf_demographics:signup_date', '{meta['signup_date']}'")
            hbase_cmds.append(f"put 'customer_rfm_features', '{cid}', 'cf_demographics:location', '{meta['location']}'")
            hbase_cmds.append(f"put 'customer_rfm_features', '{cid}', 'cf_demographics:demographic_segment', '{meta['demographic_segment']}'")
            
            # RFM
            hbase_cmds.append(f"put 'customer_rfm_features', '{cid}', 'cf_rfm:recency_days', '{recency}'")
            hbase_cmds.append(f"put 'customer_rfm_features', '{cid}', 'cf_rfm:frequency', '{freq}'")
            hbase_cmds.append(f"put 'customer_rfm_features', '{cid}', 'cf_rfm:monetary_amount', '{monetary}'")
            
            # Segmentation
            hbase_cmds.append(f"put 'customer_rfm_features', '{cid}', 'cf_segmentation:customer_segment', '{segment}'")
            hbase_cmds.append(f"put 'customer_rfm_features', '{cid}', 'cf_segmentation:is_churned', '{is_churned}'")

    with open('load_hbase.hb', 'w', encoding='utf-8') as f:
        f.write("\n".join(hbase_cmds) + "\nexit\n")
        
    print(f"Generated load_hbase.hb with {len(hbase_cmds)} HBase put commands.")

if __name__ == '__main__':
    load_data()
